#!/bin/sh

# checkall
# Terminal script to execute 'git status' on working copies
# of my public GitHub repositories in current directory

# to create:
# 1) in Terminal, cd to folder containing this script 
# 2) type 'chmod -x checkall' and hit Return to make file executable
# 3) copy this file to folder where you want to check git status of my code

# to use: 
# 1) in Terminal, cd to folder containing copied script
# 2) type './checkall' in Terminal and hit Return 
# working copies for each of my repositories, if present, will be checked

checkWC()
{
	echo '----------'
	if  [ -d $WC ]
	then
		cd $WC
		pwd
		git status
		cd ..
	else
		echo "ERROR: working copy '$WC' not found"
	fi
#	echo
}

echo
echo '----------'
echo "checking git status for working copies in '$PWD'"

WC="DebugUtil"
checkWC
WC="DevUtil"
checkWC
WC="FilesUtil"
checkWC
WC="MapUtil"
checkWC
WC="StringMapMaker"
checkWC
WC="unix-scripts"
checkWC

echo '----------'
echo "finished checkall in '$PWD'"
