#!/bin/sh

# cloneall
# Terminal script to execute 'git clone' on all my public GitHub repositories 
# to clone them into current OS X directory

# to use: 
# 1) copy this file to folder where you want to clone my code
# 2) in Terminal, cd to folder containing copied script
# 3) type './cloneall' in Terminal and hit Return 
# all six repositories will be downloaded, ready for use

git clone https://github.com/SteveCaine/DebugUtil.git
git clone https://github.com/SteveCaine/DevUtil.git
git clone https://github.com/SteveCaine/FilesUtil.git
git clone https://github.com/SteveCaine/MapUtil.git
git clone https://github.com/SteveCaine/StringMapMaker.git
git clone https://github.com/SteveCaine/unix-scripts.git
